--Magnitude analysis
-- Find total customers by countries
SELECT customer_country
	,count(*) AS total_customers
FROM gold.dimension_customers
GROUP BY customer_country

-- Find total customers by gender
SELECT customer_gender
	,count(*) AS total_customers
FROM gold.dimension_customers
GROUP BY customer_gender

-- Find total products by category
SELECT product_category
	,count(*) AS total_products
FROM gold.dimension_products
GROUP BY product_category

-- What is the average cost in each category?
SELECT product_category
	,avg(product_cost) AS avg_cost
FROM gold.dimension_products
GROUP BY product_category
-- What is the total revenue generated for each category?
WITH cte1 AS (
		SELECT product_number
			,sales_price
		FROM gold.fact_sales
		)

SELECT dp.product_category
	,sum(cte1.sales_price) AS total_revenue
FROM gold.dimension_products AS dp
INNER JOIN cte1 ON cte1.product_number = dp.product_number
GROUP BY dp.product_category
-- Find total revenue generated by each customer
WITH cte1 AS (
		SELECT customer_id
			,sum(sales_price) AS total_revenue
		FROM gold.fact_sales
		GROUP BY customer_id
		)

SELECT dc.customer_id
	,dc.customer_firstname
	,dc.customer_lastname
	,total_revenue
FROM gold.dimension_customers AS dc
LEFT JOIN cte1 ON dc.customer_id = cte1.customer_id
-- What is the distribution of sold items across countries?
WITH cte1 AS (
		SELECT dc.customer_country
			,sum(fs.sales_quantity) AS total_items_sold
		FROM gold.dimension_customers AS dc
		LEFT JOIN gold.fact_sales AS fs ON dc.customer_id = fs.customer_id
		GROUP BY dc.customer_country
		)

SELECT customer_country
	,total_items_sold
	,CONCAT (
		cast(round((cast(total_items_sold AS DECIMAL) / sum(total_items_sold) OVER ()), 2) * 100 AS NVARCHAR)
		,'%'
		) AS percent_distribution_of_quantity_items_sold
FROM cte1